"""correct ans mandotory

Revision ID: a345a2de19cb
Revises: 2a7a875fd3f2
Create Date: 2023-11-21 16:43:50.528363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a345a2de19cb'
down_revision: Union[str, None] = '2a7a875fd3f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
