apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: blob.csi.azure.com
  name: shared-data-pv
spec:
  storageClassName: azureblob-nfs-premium
  capacity:
    storage: 100Gi
  #volumeMode: Filesystem
  accessModes:
    - ReadWriteMany  # Use ReadWriteMany for shared access
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: blob.csi.azure.com
    volumeHandle: MC_cracktech_kvott_southeastasia#kuberneteslivestreaming#streamingcontainer
    volumeAttributes:
      resourceGroup: MC_cracktech_kvott_southeastasia
      storageAccount: kuberneteslivestreaming
      containerName: streamingcontainer
      protocol: nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data-pvc
spec:
  storageClassName: azureblob-nfs-premium
  accessModes:
    - ReadWriteMany  # Use ReadWriteMany to allow multiple pods to access the PVC
  resources:
    requests:
      storage: 100Gi
