apiVersion: v1
kind: Service
metadata:
  name: nginx-rtmp-service
spec:
  selector:
    app: nginx-rtmp
  ports:
  - port: 80
    name: video-output
    targetPort: video-output
  - port: 1935
    name: video-input
    targetPort: video-input
  type: LoadBalancer