apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-panel-deployment
spec:
  replicas: 1 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: control-panel
  template:
    metadata:
      labels:
        app: control-panel
      # annotations:
      #     prometheus.io/scrape: 'true'
      #     prometheus.io/port: '9113'
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: control-panel
          image: acrlivestreaming.azurecr.io/control_panel/controlpanel:second
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          ports:
          - containerPort: 3000
            name: control-expose
---
apiVersion: v1
kind: Service
metadata:
  name: control-panel-service
spec:
  selector:
    app: control-panel
  ports:
  - port: 3000
    name: control-expose
    targetPort: control-expose
  type: LoadBalancer